version: '3'
services:
  cassandra:
    image: cassandra
    container_name: cassandra
    hostname: "cassandra"
    ports:
      - "7000-7001:7000-7001"
      - "7199:7199"
      - "9042:9042"
      - "9160:9160"
    restart : on-failure:5
    environment:
      - TZ=Europe/Warsaw
  bookings_api:
    build:
      context: ./
      dockerfile: Dockerfile
    image: bookings_api
    container_name: bookings_api
    depends_on:
      - "cassandra"
    ports:
      - "8087:8087"
    restart : on-failure:10
    environment:
      - TZ=Europe/Warsaw
      - "spring.data.cassandra.contact-points=cassandra"
